.reek.yml
app/controllers/lessons_controller.rb
app/controllers/subjects_controller.rb
app/dashboards/course_dashboard.rb
app/dashboards/lesson_dashboard.rb
app/dashboards/subject_dashboard.rb
app/dashboards/user_dashboard.rb
app/models/course.rb
app/models/image.rb
app/models/lesson.rb
app/models/subject.rb
app/models/user.rb
app/models/user_course.rb
app/models/user_lesson.rb
config/initializers/simple_form_bootstrap.rb
spec/factories/images.rb

refactor smells

---

Gemfile
app/controllers/admin/lessons_controller.rb
app/controllers/admin/practices_controller.rb
app/controllers/admin/revisions_controller.rb
app/controllers/admin/theories_controller.rb
app/dashboards/lesson_dashboard.rb
app/dashboards/practice_dashboard.rb
app/dashboards/revision_dashboard.rb
app/dashboards/theory_dashboard.rb
app/models/lesson.rb
app/models/practice.rb
app/models/revision.rb
app/models/theory.rb
config/routes.rb
db/migrate/20180810090408_create_revisions.rb
db/migrate/20180810090442_create_theories.rb
db/migrate/20180810090458_create_practices.rb
db/schema.rb

Add blocks with revidion, theory, practice

---

app/controllers/admin/test_levels_controller.rb
app/dashboards/test_level_dashboard.rb
app/models/test_level.rb
app/models/user.rb
config/routes.rb
db/migrate/20180813110637_create_test_levels.rb
db/migrate/20180813131201_add_user_id_to_test_levels.rb
db/schema.rb
spec/models/test_level_spec.rb

Admin test level dashboard

---

app/controllers/admin/sub_tests_controller.rb
app/dashboards/image_question_dashboard.rb
app/dashboards/radio_image_question_dashboard.rb
app/dashboards/radio_image_text_question_dashboard.rb
app/dashboards/radio_question_dashboard.rb
app/dashboards/sub_test_dashboard.rb
app/dashboards/subject_dashboard.rb
app/dashboards/text_question_dashboard.rb
app/models/image_question.rb
app/models/page.rb
app/models/radio_image_question.rb
app/models/radio_image_text_question.rb
app/models/radio_question.rb
app/models/sub_test.rb
app/models/subject.rb
app/models/subject_sub_test.rb
app/models/text_question.rb
config/routes.rb
db/migrate/20180809200440_create_pages.rb
db/migrate/20180813175651_create_sub_tests.rb
db/migrate/20180813175923_create_subject_sub_tests.rb
db/schema.rb

Create test subjects mvc with dashboard and fix all dashboards

---

db/migrate/20180809200440_create_pages.rb
db/migrate/20180814101651_add_sub_test_to_pages.rb
db/schema.rb

Fix pages and sub_test migrations

---

app/dashboards/lesson_dashboard.rb
app/models/lesson.rb
app/models/lessons_user.rb
app/models/user.rb
db/migrate/20180816075219_create_lessons_users_join_table.rb
db/migrate/20180816100525_destroy_user_lessons_table.rb
db/migrate/20180816100700_add_index_to_lessons_users.rb
db/migrate/20180816101032_add_passed_column_to_lessons_users.rb
db/schema.rb

Update lessons_user association

---

app/assets/stylesheets/header.scss
app/views/shared/_header.html.slim
app/views/users/show.html.slim
config/locales/devise.en.yml
config/locales/devise.ru.yml
config/locales/en.yml
config/locales/ru.yml

update user dropdown, locale included

---

Gemfile.lock
db/schema.rb

Fix gemfile.lock and schema

---

app/views/static_pages/choose_level.html.slim
app/views/users/show.html.slim
config/routes.rb

fix user map pathes

---

Gemfile.lock
db/schema.rb

Update schema and gemfile

---

app/models/user.rb

Fix slugged id in admin namespace

---

app/views/admin/application/index.html.erb
config/routes.rb

Policies route

---

app/assets/stylesheets/edit_profile_page.scss
app/views/devise/registrations/edit.html.slim

Change appearance of setting page

---

app/controllers/dictionaries_controller.rb

Fix before action

---

app/controllers/courses_controller.rb
app/views/shared/_error.html.slim

Reset states of lessons in map

---

Gemfile
app/controllers/admin/questions_controller.rb
app/dashboards/question_dashboard.rb

Update lesson dashboard

---

app/assets/javascripts/lessons.js
app/controllers/answers_controller.rb

Fix lesson js code

---

app/assets/javascripts/lessons.js
app/views/answers/_image_question_form.html.slim

Get answer from question with text input

---

Gemfile
Gemfile.lock
app/assets/javascripts/lessons.js
app/controllers/admin/card_questions_controller.rb
app/dashboards/card_question_dashboard.rb
app/models/card.rb
app/models/card_question.rb
app/models/lesson.rb
app/models/question.rb
app/uploaders/avatar_uploader.rb
app/views/answers/_card_question_form.html.slim
config/initializers/carrier_wave.rb
config/routes.rb
db/migrate/20180830211453_add_lesson_id_to_cards.rb
db/schema.rb

Production fixes

---

app/assets/stylesheets/lesson.scss
config/application.rb
config/environments/production.rb

Fix assets
